"""add agent updated at

Revision ID: 0cc7d033d4a8
Revises: db380c10e690
Create Date: 2026-06-15 14:41:24.825010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc7d033d4a8'
down_revision: Union[str, Sequence[str], None] = 'db380c10e690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "agents",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE agents SET updated_at = created_at "
        "WHERE updated_at IS NULL"
    )

    op.alter_column(
        "agents",
        "updated_at",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'updated_at')
    # ### end Alembic commands ###
